name: Bug Report
description: 오류 사항에 대해서 이슈로 등록합니다
assignees:
  - yspaik
  - JaeseungYang
projects: mindsandcompany/3
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ### 프로젝트
        해당 버그가 발생한 프로젝트를 입력해주세요
        ex. 고객사 이름 / 테스트 클러스터 / 배포 클러스터 등

  - type: markdown
    attributes:
      value: |
        ### 사용자
        버그가 발생했을 당시 로그인 한 사용자 정보를 입력해주세요
        ex. administrator / 관리자

  - type: markdown
    attributes:
      value: |
        ### 버그의 증상
        발생한 증상을 써주세요.
        ex. 일부 데이터가 누락되거나 글자가 깨지는 현상

  - type: select
    attributes:
      label: 버그의 증상 발생 빈도
      description: 재현 step 대로 진행하면 항상 발생, 간헐적으로 발생
      options:
        - label: 항상 발생
          value: always
        - label: 간헐적
          value: intermittent

  - type: input
    attributes:
      label: 적용된 버전 혹은 실험한 위치
      placeholder: GenOS 운영계, 중부발전 클러스터, 한국은행 클러스터, 로컬

  - type: input
    attributes:
      label: 전처리 입력 파일
      placeholder: 예) data/input_file.csv

  - type: textarea
    attributes:
      label: 증상을 확인할 수 있는 step
      description: 버그에 대한 상세한 설명을 입력해주세요
      placeholder: |
        예) 1. 전처리 입력 파일 업로드
        2. (GenOS 운영망에서) 전처리 수동 실행
        3. Invalid Code Point 에러 메세지 확인
        
        [캡쳐를 추가해주세요]
        - 에러 메시지가 보이도록 캡쳐
        - 화면상에 보이는게 없으면 생략해도 됨

        (Optional) 개발자 도구의 Network 탭과 Console이 보이는 상태에서 해당 행동을 하고 캡쳐해주시면 더 좋습니다 :)
